/**
 * Curriculum database — typed loader and query API.
 *
 * The per-subject JSON files are generated by build.ts from raw/*.json. Import
 * from here, never from the JSON directly, so consumers get types and helpers.
 *
 *   import { concepts, search, conceptsBySubject } from '@/data/curriculum';
 */
import type {
  Concept,
  Course,
  Subject,
  GradeBand,
  Diagram3dFit,
  SubjectCurriculum,
} from './types.ts';

import mathData from './math.json' with { type: 'json' };
import physicsData from './physics.json' with { type: 'json' };
import chemistryData from './chemistry.json' with { type: 'json' };
import biologyData from './biology.json' with { type: 'json' };
import computingData from './computing.json' with { type: 'json' };

export * from './types.ts';

const subjectData: Record<Subject, SubjectCurriculum> = {
  math: mathData as SubjectCurriculum,
  physics: physicsData as SubjectCurriculum,
  chemistry: chemistryData as SubjectCurriculum,
  biology: biologyData as SubjectCurriculum,
  computing: computingData as SubjectCurriculum,
};

/** Every concept across all subjects. */
export const concepts: Concept[] = Object.values(subjectData).flatMap((s) => s.concepts);

/** Every course across all subjects. */
export const courses: Course[] = Object.values(subjectData).flatMap((s) => s.courses);

const byId = new Map(concepts.map((c) => [c.id, c]));

/** Look up a single concept by its stable id. */
export function getConcept(id: string): Concept | undefined {
  return byId.get(id);
}

/** All concepts for a subject. */
export function conceptsBySubject(subject: Subject): Concept[] {
  return subjectData[subject]?.concepts ?? [];
}

/** All concepts for a course (by display name, e.g. "AP Physics 1"). */
export function conceptsByCourse(courseName: string): Concept[] {
  return concepts.filter((c) => c.course === courseName);
}

/** All concepts in a grade band. */
export function conceptsByGradeBand(band: GradeBand): Concept[] {
  return concepts.filter((c) => c.gradeBand === band);
}

/** Resolve a concept's prerequisites to concept objects (skips any unknown id). */
export function prerequisitesOf(id: string): Concept[] {
  const c = byId.get(id);
  if (!c) return [];
  return c.prerequisites.map((p) => byId.get(p)).filter((x): x is Concept => !!x);
}

/**
 * Concepts best suited to an interactive 3D diagram. Defaults to "high" fit —
 * the natural seed list for building the first diagrams.
 */
export function diagram3dCandidates(minFit: Diagram3dFit = 'high'): Concept[] {
  const rank: Record<Diagram3dFit, number> = { none: 0, low: 1, medium: 2, high: 3 };
  return concepts.filter((c) => rank[c.diagram3dFit] >= rank[minFit]);
}

/**
 * Free-text search over title, description, keywords, course, and unit.
 * Simple case-insensitive substring match — good enough for classification and
 * autocomplete; swap for a real index later if needed.
 */
export function search(query: string): Concept[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return concepts.filter((c) => {
    const hay = [
      c.title,
      c.description,
      c.course,
      c.unit,
      ...c.keywords,
    ]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

/** Aggregate counts, handy for dashboards / coverage reports. */
export function stats() {
  const subjects = Object.keys(subjectData) as Subject[];
  return {
    totalConcepts: concepts.length,
    totalCourses: courses.length,
    bySubject: Object.fromEntries(
      subjects.map((s) => [s, subjectData[s].concepts.length]),
    ) as Record<Subject, number>,
    byDiagram3dFit: concepts.reduce(
      (acc, c) => ((acc[c.diagram3dFit] = (acc[c.diagram3dFit] ?? 0) + 1), acc),
      {} as Record<Diagram3dFit, number>,
    ),
  };
}
